config:
  generate_resource_id: true
  pass_query_string: true
  payloads_path: payloads/
  use_error_handler: true
  cors:
    enabled: true
    headers:
      - X-Operation
      - X-Resource
      - X-Total-Count
  authentication:
    type: jwt
    global: true
    jwt:
      key: JLBMU2VbJZmt42sUwByUpJJF6Y5mG2gPNU9sQFUpJFcGFJdyKxskR3bxh527kax2UcXHvB
      issuer: dshop-identity-service
      issuers:
      validate_issuer: true
      audience:
      audiences:
      validate_audience: false
      validate_lifetime: false
    claims:
        role: http://schemas.microsoft.com/ws/2008/06/identity/claims/role
    policies:
      admin:
        role: admin
      product_manager:
        role: merchant
        access: create_product
        
extensions:
  dispatcher:
    use: rabbitmq_dispatcher

routes:
  home:
  - upstream: /
    method: GET
    use: return_value
    return_value: "Welcome to API Gateway"
    auth: false
  products:
  - upstream: /products
    method: GET
    use: downstream
    downstream: products-service/products
  - upstream: /products/{productId}
    method: GET
    use: downstream
    downstream: products-service/products/{productId}
  - upstream: /products
    method: POST
    use: dispatcher
    exchange: "products.create_product"
    routing_key: "create_product"
    payload: create_product.json
    scheme: create_product.scheme.json
    claims:
      role: admin
    policies:
      - product_manager
    
  orders:
  - upstream: /orders
    method: GET
    use: downstream
    downstream: https://api.42.do/training/plans.json
  - upstream: /orders/{orderId}
    method: GET
    use: downstream
    downstream: orders-service/orders/{orderId}
  - upstream: /orders
    method: POST
    use: dispatcher
    exchange: "orders.create_order"
    routing_key: "create_order"
    set:
      - customerId:{user_id}
    transform:
      - test:nothing
    payload: create_order.json
    scheme: create_order.scheme.json
  - upstream: /orders/sync/{orderId}
    generate_resource_id: true
    method: POST
    downstream_method: PUT
    use: downstream
    downstream: orders-service/orders/{orderId}
    set:
    - customerId:{user_id}
    transform:
    - customerId:user
    payload: "create_order.json"

services: 
  products-service:
    url: localhost:9999/products-service
  orders-service:
    url: localhost:9999/orders-service
