config:
  generate_resource_id: true
  authentication:
    type: jwt
    global: true
    issuer: dshop-identity-service
    key: JLBMU2VbJZmt42sUwByUpJJF6Y5mG2gPNU9sQFUpJFcGFJdyKxskR3bxh527kax2UcXHvB

extensions:
  dispatcher:
    use: rabbitmq_dispatcher

routes:
  home:
  - path: /
    method: GET
    type: local
    return: "Welcome to API Gateway"
    auth: false
  products:
  - path: /products
    method: GET
    type: request
    upstream: products-service/products
  - path: /products/{productId}
    method: GET
    type: request
    upstream: products-service/products/{productId}
  - path: /products
    method: POST
    type: dispatcher
    exchange: "products.create_product"
    routing_key: "create_product"
    payload: create_product.json
    scheme: create_product.scheme.json
    claims:
      - admin
  orders:
  - path: /orders
    method: GET
    type: request
    upstream: https://api.42.do/training/plans.json
  - path: /orders/{orderId}
    method: GET
    type: request
    upstream: orders-service/orders/{orderId}
  - path: /orders
    method: POST
    type: dispatcher
    exchange: "orders.create_order"
    routing_key: "create_order"
    set:
      - customerId:{user_id}
    transform:
      - test:nothing
    payload: create_order.json
    scheme: create_order.scheme.json
  - path: /orders/sync
    generate_resource_id: true
    method: POST
    upstream_method: PUT
    type: request
    upstream: orders-service/orders/{orderId}
    set:
    - customerId:{user_id}
    transform:
    - customerId:user
    payload: "create_order.json"

services: 
  products-service:
    url: localhost:9999/products-service
  orders-service:
    url: localhost:9999/orders-service
